### ISSUE TITLE
New stubs class generate class definition conflict with existing classes in downstream project

### ISSUE THREAD

**Issue by iNem0o** [jolicode/castor#553]
**Context**
Project using PHPStan for static analysis on Castor tasks, the stub file is included in phpstan.neon using the bootstrapFiles directive:

```
parameters:
    bootstrapFiles:
        - .castor.stub.php
```

**Problem** 
Since the latest release, running PHPStan with the included stub results in a fatal error because some class included here https://github.com/jolicode/castor/blob/main/src/Stub/StubsGenerator.php#L81 could already be present in the current execution context

I would like to establish the best way to solve that problem and then I could try to submit a PR to resolve the problem.

**Comment by pyrech** [comment]
Not sure to see why this would break on latest release only. Unless I'm wrong, the stubs changed on #536 only to fix the the PHPDoc not using FQCN, but the array of frequently used classes you mention did not change (we also removed some privacy props/method/const from the stubs and added some Castor internal classes, but nothing else related to vendor classes).

What was the exact error you faced?

**Comment by iNem0o** [comment]
Hello @pyrech you are right sorry for the misunderstanding, i updated from [v0.18.2] to [v0.19.0]

The problem i am facing is when i run phpstan using the stub as bootstrapFiles on a project already using classes in the frequently used classes array i get the following error : 
`Fatal error: Cannot declare class Symfony\Component\Console\Application, because the name is already in use in /app/.castor.stub.php on line 1108`

**Comment by lyrixx** [comment]
Is it fixed by https://github.com/jolicode/castor/pull/552?

**Comment by iNem0o** [comment]
Hello @lyrixx

Same behavior with #552 the `Symfony\Component\Console\Application` class stub still present in the generated file.

**Comment by pyrech** [comment]
I was trying to reproduce your issue but without luck. Then I figured that on our projects, we confgure phpstan like this:

```
parameters:
    scanFiles:
        - .castor.stub.php
```

According to [PHPStan documentation](https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies), `scanFiles` seems more appropriate to load stub files. Could you confirm whether if it solves your issues?

**Comment by iNem0o** [comment]
thanks for the finding @pyrech this is working perfectly.
